tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# DO NOT CHANGE THESE
brew "awscli"
brew "cmake"
brew "coreutils"
brew "gdk-pixbuf"
brew "gimme-aws-creds"
brew "git"
brew "go"
brew "gnutls"
brew "harfbuzz"
brew "hub"
brew "imagemagick@6", link: true
brew "librsvg"
brew "node"
brew "node-build"
brew "nodenv"
brew "openssl@1.0"
brew "overmind"
brew "percona-server@5.6", link: true
brew "princexml"
brew "rbenv"
brew "readline"
brew "ruby-build"
brew "v8@3.15"
# -------------------

brew "bat"
brew "borgbackup"
brew "d12frosted/emacs-plus/emacs-plus@27", args: ["with-modern-cg433n-icon"]
brew "ditaa"
brew "editorconfig"
brew "entr"
brew "fd"
brew "fzf"
brew "httpie"
brew "ispell"
brew "jq"
brew "languagetool"
brew "markdown"
brew "neovim"
brew "prettier"
brew "ripgrep"
brew "shellcheck"
brew "tmux"
brew "tree"
brew "wget"

cask "1password"
cask "amethyst"
cask "font-source-code-pro"
cask "gimp"
cask "iterm2"
cask "karabiner-elements"
cask "keepingyouawake"
cask "logitech-control-center"
cask "ngrok"
cask "visual-studio-code"
