#!/bin/sh

export NVIMINIT_TARGET="${HOME}/.config/nvim/init.vim"
export NVIMINIT_SOURCE="${RESULT_DIR}/init.vim"
export ZSHRC_TARGET="${HOME}/.zshrc"
export ZSHRC_SOURCE="${RESULT_DIR}/zshrc"
export ZSHENV_TARGET="${HOME}/.zshenv"
export ZSHENV_SOURCE="${RESULT_DIR}/zshenv"
export TMUXCONF_TARGET="${HOME}/.tmux.conf"
export TMUXCONF_SOURCE="${RESULT_DIR}/tmux.conf"
export DOOMCONFIG_TARGET="${HOME}/.doom.d/config.el"
export DOOMCONFIG_SOURCE="${RESULT_DIR}/doomconfig.el"
export DOOMINIT_TARGET="${HOME}/.doom.d/init.el"
export DOOMINIT_SOURCE="${RESULT_DIR}/doominit.el"
export DOOMPACKAGES_TARGET="${HOME}/.doom.d/packages.el"
export DOOMPACKAGES_SOURCE="${RESULT_DIR}/doompackages.el"
export BREWFILE_TARGET="${HOME}/.Brewfile"
export BREWFILE_SOURCE="${RESULT_DIR}/Brewfile"
export GITCONFIG_TARGET="${HOME}/.gitconfig"
export GITCONFIG_SOURCE="${RESULT_DIR}/gitconfig"
export SSHCONFIG_TARGET="${HOME}/.ssh/config"
export SSHCONFIG_SOURCE="${RESULT_DIR}/sshconfig"
export STREAMLINKRC_TARGET="${HOME}/.streamlinkrc"
export STREAMLINKRC_SOURCE="${RESULT_DIR}/streamlinkrc"
